export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const ID_ACTIVE = "ID_ACTIVE";
export const FILTER_SERVICE = "FILTER_SERVICE";

export default {
  ADD_SERVICE,
  REMOVE_SERVICE,
  CHANGE_SERVICE_FIELD,
  ID_ACTIVE,
  FILTER_SERVICE
};