export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const ID_ACTIVE = "ID_ACTIVE";

export default {
  ADD_SERVICE,
  REMOVE_SERVICE,
  CHANGE_SERVICE_FIELD,
  ID_ACTIVE,
};